import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteNav from "@/components/site-nav";
import SiteFooter from "@/components/site-footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<body
  className={`${geistSans.variable} ${geistMono.variable} min-h-full antialiased`}
>
  <div className="min-h-screen flex flex-col">
    <div className="fixed left-0 right-0 top-0 z-50 px-6">
      <SiteNav />
    </div>

    <main className="flex-1">
      {children}
    </main>

    <SiteFooter />
  </div>
</body>
    </html>
  );
}
